### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dalailama100** [noam09/deluge-telegramer#10]
Hey noam, 
I love this plugin. It works really well and is very stable. 
Would it be possible to add a feature enabling notifications for users other than just the bot owner? Maybe giving the additional ID's this feature would be easy?
Many thanks.

**Comment by noam09** [comment]
Hey, glad you like the plugin! :)
This could definitely be implemented. I'll give it a go some time soon, just have to find the time.

**Comment by noam09** [comment]
Hey @dalailama100, please try out the [latest release](https://github.com/noam09/deluge-telegramer/releases) and let me know what you think. There may be some bugs, so just a heads up.

**Comment by dalailama100** [comment]
Hey noam09,
I installed the new release last night. Put in my friend's notify ID and it works like a charm.
Great work. If any bugs do happen to show, I will post.
Thank you for programming this feature in record time! Absolutely amazing!

**Comment by noam09** [comment]
My pleasure. Closing for now, reopen if bugs are found. :)

**Comment by noam09** [comment]
@dalailama100 I just released a [new .egg](https://github.com/noam09/deluge-telegramer/releases/tag/v1.1.7.1) that addresses a bug I found with message sending.

**Comment by dalailama100** [comment]
Hey noam09,
I noticed that when I try using the commands  /help, /down and /up commands, they don't seem to currently work under the new version Telegramer-1.1.7.1.
The /add command works fine.
Cheers!

**Comment by noam09** [comment]
I noticed that as well, working on a fix soon. Thanks for pointing it out.

**Comment by noam09** [comment]
Pushed a fix, will upload a new .egg later today.

**Comment by noam09** [comment]
[It's up](https://github.com/noam09/deluge-telegramer/releases/tag/v1.1.7.2). @dalailama100 care to try?

**Comment by dalailama100** [comment]
Hey noam09,
Just updated, all is good. The commands are functioning again.
