### ISSUE TITLE
[Feature Request] Custom Notification Message

### ISSUE THREAD

**Issue by Generator** [noam09/deluge-telegramer#16]
### Description 
Ability to personalize the notification text (with HTML or Markdown).

### Expected Behavior
[HTML] **Custom Message:** 
```
<b>Foobar</b>
Downloaded: <b>{TorrentName}</b>
```
                              
[Markdown] **Custom Message:** 
```
**Foobar**
Downloaded: `{TorrentName}`
```

**Comment by noam09** [comment]
Hi @Generator - I know this is a bit old, but feel free to try out the [latest Alpha release](https://github.com/noam09/deluge-telegramer/releases/download/v1.2.1-alpha/Telegramer-1.2.1.7-alpha-py2.7.egg) which adds this feature.

**Comment by Generator** [comment]
I'm using Deluge 2.x, no longer supports python2 plugins.
