### ISSUE TITLE
[Feature Request] adding torrent without commands

### ISSUE THREAD

**Issue by kon-git** [noam09/deluge-telegramer#19]
**Describe the solution you'd like**
Throw a new .torrent file to telegramer, and telegramer adds the torrent to deluge without asking further questions. (with no label, using default settings)

**Additional context**

[As of now]
1. Download a .torrent file with Safari(iOS).
2. Switch to telegram app, find Telegramer bot, and enter commands.
3. Switch back to Safari, and share(send) .torrent file to Telegramer.
4. Telegramer adds the torrent to Deluge.

[I'd like]
1. Download a .torrent file with Safari, and share(send) it to Telegramer.
3. Telegramer adds the torrent to Deluge.

Great plugin, Thank you noam!

**Comment by noam09** [comment]
Hi @kon-git, the [latest alpha release](https://github.com/noam09/deluge-telegramer/releases/tag/v1.2.1-alpha) features this ability. Feel free to try it out and post back here if you encounter any issues.

**Comment by kon-git** [comment]
@noam09 
Thanks for the update!

I tried the latest alpha release(1.2.1-alpha) yet wasn't able to install it.
The .egg file was uploaded to the server, but when I 'enable' telegramer and hit apply button, the 'enabled' checkbox turns off automatically.

I re-installed the stable version (1.2) and it works well.

**Comment by noam09** [comment]
That usually happens when there's an exception. 
I've just uploaded an [`.egg` with debugging enabled](https://github.com/noam09/deluge-telegramer/releases/download/v1.2.1-alpha/Telegramer-1.2.1.1-alpha-debug-py2.7.egg). 

Could you please try running Deluge with `deluged -L debug -l <logfile>` and posting the error/exception from the log file here? _Make sure to remove any sensitive info from the log (names, paths, tokens)._

To narrow it down, you can run `tail -f <logfile>` and watching the output as soon as you install and enable the new egg (any errors before that are probably irrelevant). 

It might help to try the new install after restarting Deluge, maybe even remove the "bad" egg from Deluge's directory (by default `~/.config/deluge/plugins/Telegramer...`).

**Comment by kon-git** [comment]
I'm sorry, actually I'm using docker (linuxserver/deluge) and I have no idea how to create detailed logfile from docker container.
I did a quick google search and tried `sudo docker logs -f deluge --details`, but couldn't find any line regarding telegramer(1.2.1.1).


```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
 [s6-init] ensuring user provided files have correct perms...exited 0.
 [fix-attrs.d] applying ownership & permissions fixes...
 [fix-attrs.d] done.
 [cont-init.d] executing container initialization scripts...
 [cont-init.d] 10-adduser: executing...

 -------------------------------------
           _         ()
          | |  ___   _    __
          | | / __| | |  /  \
          | | \__ \ | | | () |
          |_| |___/ |_|  \__/


 Brought to you by linuxserver.io
 We gratefully accept donations at:
 https://www.linuxserver.io/donate/
 -------------------------------------
 GID/UID
 -------------------------------------
 usermod: no changes

 User uid:    1000
 User gid:    1000
 -------------------------------------

 [cont-init.d] 10-adduser: exited 0.
 [cont-init.d] 30-config: executing...
 [cont-init.d] 30-config: exited 0.
 [cont-init.d] done.
 [services.d] starting services
 [services.d] done.
 [INFO    ] 00:09:32 configmanager:70 Setting config directory to: /config
 [INFO    ] 00:09:32 ui:124 Deluge ui 1.3.15
 [INFO    ] 00:09:32 ui:127 Starting web ui..
 [INFO    ] 00:09:33 server:666 Starting server in PID 216.
 [INFO    ] 00:09:33 server:679 Serving on 0.0.0.0:8112 view at http://0.0.0.0:8112
 [INFO    ] 00:09:35 client:217 Connecting to daemon at 127.0.0.1:58846..
 [INFO    ] 00:09:35 client:217 Connecting to daemon at 127.0.0.1:58846..
 [INFO    ] 00:09:35 client:121 Connected to daemon at 127.0.0.1:58846..
 [INFO    ] 00:09:35 client:121 Connected to daemon at 127.0.0.1:58846..
 [INFO    ] 00:09:35 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection was closed cleanly.
 [INFO    ] 00:09:35 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection was closed cleanly.
 [INFO    ] 00:09:44 client:217 Connecting to daemon at 127.0.0.1:58846..
 [INFO    ] 00:09:44 client:121 Connected to daemon at 127.0.0.1:58846..
 [INFO    ] 00:09:44 pluginmanagerbase:158 Plugin Label enabled..
 [INFO    ] 00:09:44 pluginmanagerbase:158 Plugin MoveTools enabled..
 [INFO    ] 00:09:44 pluginmanagerbase:158 Plugin AutoRemovePlus enabled..
 [INFO    ] 00:09:44 pluginmanagerbase:158 Plugin LabelPlus enabled..

```

**Comment by noam09** [comment]
I see, if you try running it the same way, but using the debug egg I mentioned - do you see more logs?

**Comment by kon-git** [comment]
Actually I already used debug version(Telegramer-1.2.1.1-alpha-debug-py2.7) from above. 
Tried again but nothing more...

**Comment by noam09** [comment]
I'll try running the same container and seeing what results I get, but it'll probably take me a while to get to. See if you can set the log level and/or view more detailed logs from within the container (`docker exec -it deluge /bin/bash`).

**Comment by noam09** [comment]
@kon-git have you had a chance to try the [latest build](https://github.com/noam09/deluge-telegramer/releases/download/v1.2.1-alpha/Telegramer-1.2.1.6-alpha-debug-py2.7.egg)?

**Comment by kon-git** [comment]
@noam09 Hi, I've just tried the latest build 1.2.1.6 alpha-debug. It works!
Have no idea why it didn't work the last time I tried though... settings were pretty much same. 

Thank you 😄

**Comment by noam09** [comment]
Well, I fixed a few issues in the code, so it probably wasn't something on your end. Just to clarify - does adding a torrent without commands work for you?

**Comment by noam09** [comment]
Re-open if needed
