### ISSUE TITLE
following install tutorial in README does not work

### ISSUE THREAD

**Issue by viktor-c** [noam09/deluge-telegramer#2]
Hi noam09!
Love your app, thank you so much for this super plugin!
I had one problem after following your install tutorial : The Telegram plugin did not start, i could see that, because in the left side panel, Telegramer did not show up. Eventually pinned the problem to TelegramBotAPI. The problem was, it was installed with pip using my main account, but deluge runs on user deluge. So the plugin would not find the needed API.

Anyway, go to the folder where Telegramer was downloaded to, install dependencies and compile eggshell
After that, run 
sudo pip install -e .

Working flawlessly after that!

**Comment by noam09** [comment]
Hey @viktor-c, thank you for pointing this out. 
If you run `pip show pyTelegramBotAPI`, what path shows up under _Location_? When you install packages using your main account, are they installed under a specific user's home directory?

**Comment by viktor-c** [comment]
Running `pip show pyTelegramBotAPI` gives me a local directory. So I guess the packages get installed on my normal user, but deluge is configured to use a separate user without privileges.
Thanks for the great app!

**Comment by noam09** [comment]
I updated the installation instructions to address this issue, I believe you can install packages globally (system-wide) by installing as root:
`sudo su`
`pip install pyTelegramBotAPI`
`exit`
