### ISSUE TITLE
[Feature Request] Deluge 2.0 support

### ISSUE THREAD

**Issue by dbutrimov** [noam09/deluge-telegramer#22]
Deluge 2.0 released.

> Plugins written for Deluge 1.3 will need upgrading for Deluge 2.0, due to the requirement of Python 3 and GTK3 UI. There is a [update plugin](https://deluge.readthedocs.io/en/latest/devguide/how-to/update-1.3-plugin.html) document to help Plugin authors update their plugins.

**Comment by noam09** [comment]
Hey @dbutrimov, thanks for the heads-up. This will probably require some time and debugging to get working, so unfortunately it will probably be a while before I have the time to get working on it. 

I'd also like to make sure the latest commits in the `develop` branch are stable before I even begin to look into v2 integration. 

Needless to say, any Pull Requests for v2 integration are welcome. Just make sure to work on them in a separate branch, derived off of the ~~`develop`~~ [`python3` branch](https://github.com/noam09/deluge-telegramer/tree/python3).

**Comment by HydrelioxGitHub** [comment]
Any news on this ?

**Comment by springjools** [comment]
I can have a look and see what I can achieve. I already updated another plugin for deluge 2.0. 

(Note that if using python 3.8 or above, even deluge 2.0 isn't enough, you need the dev version of deluge.)

**Comment by springjools** [comment]
Also note that instead of using deluge to send notifications, you can use sonarr/radarr/lidarr to do the same thing. It might be a better option since sonarr et al have a very active development team, more active than that of deluge, which itself needs more critical fixes to be made.

**Comment by noam09** [comment]
> I can have a look and see what I can achieve. I already updated another plugin for deluge 2.0.
> 
> (Note that if using python 3.8 or above, even deluge 2.0 isn't enough, you need the dev version of deluge.)

Thanks for offering! If you have the time to make the transition to Deluge 2, that would be awesome. :+1: 
I'll create a ["py3" branch](https://github.com/noam09/deluge-telegramer/tree/python3) that you can fork to keep it organized.

**Comment by chrismast** [comment]
Hi, is there any progress on a v2.0 plugin yet?

**Comment by springjools** [comment]
Hey. Sorry, I cannot commit to more projects now, just started a new job and all my time goes to it and existing projects. Hope someone else is keen on it though :)

**Comment by springjools** [comment]
I'm also using sonarr and radarr and they come with telegram support.

**Comment by chrismast** [comment]
@springjools no worries. Also using both with telegram which works fine. Thanks for your reply though.

**Comment by OfryL** [comment]
@noam09 maybe we can raise some money for this

**Comment by noam09** [comment]
> @noam09 maybe we can raise some money for this

I appreciate the offer, but there is no need. :) 

I've started working on this, I hope to have a release for testing soon. I'll update this issue once it's up. Sorry it took this long, I realize it's been a very long time since this was requested.

**Comment by noam09** [comment]
Beta version released: https://github.com/noam09/deluge-telegramer/releases/tag/v2.0.5.0
I haven't had a chance to thoroughly test it yet. Please try it out and [create an issue](https://github.com/noam09/deluge-telegramer/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+) for any bugs you find. Thanks!

**Comment by Ob1w4** [comment]
Hey,

I am currently using the plugin with Deluge 1.3.5 and it works great. But I am tempted to upgrade to Deluge 2.x and have two questions:

1) The version I can install is Deluge 2.0.3. I see that deluge-telegramer has a beta version with Deluge 2.0.5 support. Can you still use this version with Deluge 2.0.3 or is it only for 2.0.5?

2) I see that it requires Python 3.8 or 3.10. Currently, I have Python 3.7.3 and can't update (I don't control this). Will the .egg for 3.8 eventually work or do I need a specific .egg 3.7 version (which doesn't exist)?

Thank you!

**Comment by noam09** [comment]
> Hey,
> 
> I am currently using the plugin with Deluge 1.3.5 and it works great. But I am tempted to upgrade to Deluge 2.x and have two questions:
> 
> 1. The version I can install is Deluge 2.0.3. I see that deluge-telegramer has a beta version with Deluge 2.0.5 support. Can you still use this version with Deluge 2.0.3 or is it only for 2.0.5?
> 2. I see that it requires Python 3.8 or 3.10. Currently, I have Python 3.7.3 and can't update (I don't control this). Will the .egg for 3.8 eventually work or do I need a specific .egg 3.7 version (which doesn't exist)?
> 
> Thank you!

Hey @Ob1w4, I must have missed your comment, sorry about that. Please try out the 3.7 egg in the [latest](https://github.com/noam09/deluge-telegramer/releases/latest) release. I believe the Deluge 2.1.1-compatible version should also work with 2.0.3, or any Deluge 2+ for that matter. Please open an issue if it doesn't work, I'll be happy to take a look.
