### ISSUE TITLE
[BUG] not sending notifications about added and finished torrents

### ISSUE THREAD

**Issue by bggergo29** [noam09/deluge-telegramer#26]
**Describe the bug**
If I upload the torrent file with the Telegram bot, I do not get the "Upload finished" and "Torrent finished" messages. Everything works well, except this feature. I've checked the checkboxes at the Notifications.

**To Reproduce**
Add a torrent using telegramer
**Screenshots**
![image](https://user-images.githubusercontent.com/34211420/104092862-043b7480-5287-11eb-9337-d0a05e7790e9.png)

**OS and Version:**
 - OS: Raspberry Pi OS
 - Deluge version: 1.3.15
 - Bot version: v1.2.1-alpha
 
**Edit:**
It is only happening if I try to upload a torrent file through the telegram bot.

**Comment by noam09** [comment]
Hey @bggergo29, thanks for reporting this issue.

1. If you add a torrent from the Deluge UI, are notifications sent from the bot?
1. Notifications are not sent *only* if the torrent was added through the bot itself?
1. Does the same happen with Magnet links? Does this happen using [this torrent (21MB)](https://distrowatch.com/dwres/torrents/TinyCore-current.iso.torrent)?
1. Did you set a custom notification message in the settings? If so, what exactly did you set?
1. Do the Deluge debug logs show any errors at the same time notifications should be sent? Debug logs can be produced by running Deluge as such: `deluge -L debug -l <log_file_path>` (make sure to censor any sensitive info).

**Comment by bggergo29** [comment]
Thanks for the support, it works now, it was my mistake. I'm really sorry for wasting your time with this false issue.
Gergő

**Comment by noam09** [comment]
All good, no worries. 👍
