### ISSUE TITLE
[BUG] /cancel command doesn't work          

### ISSUE THREAD

**Issue by ghost** [noam09/deluge-telegramer#28]
It just shows that the operation has been canceled but doesn't really do so.

**Comment by noam09** [comment]
Hi @Zsasz1713, when you say that you cancel but it "doesn't really do so", what exactly do you mean? What remains in progress although it should have been cancelled? Just to clairfy, the purpose of `/cancel` is to abort the addition of a new torrent while in the process of selecting options (category, path, label, etc.).

**Comment by Zsasz1713** [comment]
> Hi @Zsasz1713, when you say that you cancel but it "doesn't really do so", what exactly do you mean? What remains in progress although it should have been cancelled? Just to clairfy, the purpose of `/cancel` is to abort the addition of a new torrent while in the process of selecting options (category, path, label, etc.).

**Comment by ghost** [comment]
@noam09 It seems like I misunderstood the function. I thought /cancels cancels the download. Sorry for the inconvenience.
I request you please add pause/resume commands.
