### ISSUE TITLE
Add more Telegram ID's to control the TelegramBot

### ISSUE THREAD

**Issue by viktor-c** [noam09/deluge-telegramer#3]
Would it be possible to add in the deluge plugin a text area to input more Telegram ID's, which allow to control the Bot, respectively add torrents

Thank you!
Victor

**Comment by noam09** [comment]
Hey @viktor-c, that's a great idea and it's actually in my to-do list. :) 
Should be available soon.

**Comment by viktor-c** [comment]
Can't wait! Thank you!

Am 19.11.2016 21:47 schrieb "Noam" notifications@github.com:

**Comment by noam09** [comment]
Latest commit adds this ability. Please give it a try and let me know how it works.

**Comment by viktor-c** [comment]
Thank you! Works as intended.
