### ISSUE TITLE
[BUG] up down commands not working

### ISSUE THREAD

**Issue by mohitjoshi155** [noam09/deluge-telegramer#33]
09:22:51 [WARNING ][deluge.plugin.telegramer.core      :362 ] Update "{'message': {'new_chat_photo': [], 'photo': [], 'entities': [{'type': 'bot_command', 'length': 3, 'offset': 0}], 'text': '/up', 'message_id': 96, 'group_chat_created': False, 'supergroup_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'delete_chat_photo': False, 'date': 1651828971, 'channel_chat_created': False, 'chat': {'first_name': '', 'type': 'private', 'last_name': '', 'username': '', 'id': }, 'from': {'last_name': '', 'first_name': '', 'language_code': 'en', 'username': '', 'id': red, 'is_bot': False}}, 'update_id': 782976158}" caused error "'bool' object is not iterable"

up ,down and list commands are giving errors

**Comment by tallevi1000** [comment]
same issue here.
running deluge on a docker with the python 3.10 egg version.
can you kindly share ETA on this?

**Comment by noam09** [comment]
Hey @mohitjoshi155 and @tallevi1000
Thanks for reporting this, I am able to reproduce the issue. Looking into it.

**Comment by tallevi1000** [comment]
thanks for the quick reply.
btw, the /list, /up, /down, /paused commands work fine when the deluge client is empty.
its only when there is at least 1 torrent (doesnt matter in which state), commands dont work.

**Comment by tallevi1000** [comment]
Hi @noam09  can you please share status on this? Maybe we can help? 😊

**Comment by DeepZeepOk** [comment]
Has anyone solved this problem?

**Comment by tallevi1000** [comment]
> Has anyone solved this problem?

no. im looking into other plugins to either manage my deluge or maybe even switching to another client with a decent bot...

**Comment by noam09** [comment]
Sorry for the delay. IIRC I started looking into this and kind of hit a brick wall.
I will get back to it hopefully this week, maybe I overlooked something.

**Comment by noam09** [comment]
Releasing a fix soon.

**Comment by noam09** [comment]
Please try out the latest release `egg` according to your Python version and comment here with any issues you find.

https://github.com/noam09/deluge-telegramer/releases/latest

**Comment by DeepZeepOk** [comment]
Thanks a lot! This problem is gone, now everything works great.
