### ISSUE TITLE
[BUG] Categories/Directories aren't working

### ISSUE THREAD

**Issue by ToshipSo** [noam09/deluge-telegramer#34]
**Categories and Directories aren't getting saved in preferences.**
I'm specifying Categories and directories and they are not getting saved properly. When I restart the deluged server I see the fields empty. Apart from that when using the telegram bot when using /add command when I specify the category it doesn't download torrent in the specified directory instead it downloads it in the default directory.

**To Reproduce**
1. Go to 'prefrences'
2. Click on 'Telegramer tab'
3. Fill 'Categories and directories section'
4. Click on 'Apply' and 'Ok'

**Expected behavior**
The config should be saved and on adding torrent through telegram bot after specifying category it should download torrent in the corresponding directory.

**Logs**
[DEBUG   ] 21:13:18 connectionpool:835 Starting new HTTPS connection (10): api.telegram.org
[DEBUG   ] 21:13:19 core:1138 2022-05-29 21:13:19 # Telegramer: Get config
[DEBUG   ] 21:13:21 core:1113 2022-05-29 21:13:21 # Telegramer: Set config
[ERROR   ] 21:13:21 rpcserver:306 Exception calling RPC request: 'cat1'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 301, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/home/deluge/.config/deluge/plugins/Telegramer-1.3.1-py2.7.egg/telegramer/core.py", line 1117, in set_config
    self.config[key] != config[key]:
  File "/usr/lib/python2.7/dist-packages/deluge/config.py", line 245, in __getitem__
    return self.get_item(key)
  File "/usr/lib/python2.7/dist-packages/deluge/config.py", line 263, in get_item
    if isinstance(self.__config[key], str):
KeyError: 'cat1'
[DEBUG   ] 21:13:23 updater:326 Timed out getting Updates: Timed out
[DEBUG   ] 21:13:23 bot:74 Entering: get_updates
[DEBUG   ] 21:13:23 connectionpool:835 Starting new HTTPS connection (11): api.telegram.org

**OS and Version:**
 - OS: Ubuntu 18.04
 - Deluge version: 1.3.15
 - Telegrammer version: 1.3.1

**Comment by noam09** [comment]
Hey @ToshipSo, thanks for reporting this. 

First of all, I should clarify that the Categories feature uses Deluge's "Move on Completion" feature to set the download directory. So the download itself is saved to the default directory, and only after it has finished downloading will it move the files to the directory specified in "Category". 

Do you have a directory path set in only one of the category rows? Are the unused rows kept empty?
