### ISSUE TITLE
[BUG]  telegramer.conf missing

### ISSUE THREAD

**Issue by itdtamas** [noam09/deluge-telegramer#35]
**Describe the bug**
 Unable to open config file /volume1/@appstore/deluge/var/telegramer.conf: [Errno 2] No such file or directory: '/volume1/@appstore/deluge/var/telegramer.conf'

**To Reproduce**
1. Go to install egg
2. Click on Telegramer
3. Scroll down to not see in the left side

**Screenshots**
![image](https://user-images.githubusercontent.com/100582025/174083359-8be802da-e6e8-4f9d-bfaa-7321697bb1bb.png)

**Logs**
15:40:49 [ERROR   ][deluge                                             :58  ] Appending to sys.path: '/volume1/@appstore/deluge/var/plugins/Telegramer-1.3.1-py2.7.egg/telegramer/include'
15:40:50 [INFO    ][deluge.plugin.telegramer.core                        :226 ] 2022-06-16 15:40:50 # Telegramer: Enable
15:40:50 [WARNING ][deluge.config                                        :410 ] Unable to open config file /volume1/@appstore/deluge/var/telegramer.conf: [Errno 2] No such file or directory: '/volume1/@appstore/deluge/var/telegramer.conf'
15:40:50 [INFO    ][deluge.pluginmanagerbase                             :189 ] Plugin Telegramer enabled...

**OS and Version:**
 - OS: Linux
 - Deluge version: 2.0.3-13

**Comment by noam09** [comment]
Hey @itdtamas 
Looking at the logs, it seems like you're trying to load `Telegramer-1.3.1-py2.7.egg`, yet you are using Deluge 2.0.3.
Please try using this version of the plugin: https://github.com/noam09/deluge-telegramer/releases/tag/v2.0.5.0
It was built for Deluge 2.0.5 but maybe it will also work with 2.0.3.

**Comment by itdtamas** [comment]
Hi @noam09 
It's working! Many thanks!
