### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'Telegramer' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by dkgitdev** [noam09/deluge-telegramer#37]
Hello. I've installed [latest beta](https://github.com/noam09/deluge-telegramer/releases/download/v2.0.5.0/Telegramer-2.0.5.0-py3.8.egg)

This is what I get after trying to tick the plugin. The plugin checkbox remains empty and the plugin is inactive.

```
19:12:03 [ERROR   ][deluge.pluginmanagerbase          :72  ] Unable to instantiate plugin 'Telegramer' from 'c:\\users\\dk\\appdata\\roaming\\deluge\\plugins\\telegramer-2.0.5.0-py3.8.egg'!
19:12:03 [ERROR   ][deluge.pluginmanagerbase          :72  ] The 'Telegramer' distribution was not found and is required by the application
Traceback (most recent call last):
  File "deluge\pluginmanagerbase.py", line 148, in enable_plugin
  File "c:\users\dk\appdata\roaming\deluge\plugins\telegramer-2.0.5.0-py3.8.egg\telegramer\__init__.py", line 64, in __init__
    load_libs()
  File "c:\users\dk\appdata\roaming\deluge\plugins\telegramer-2.0.5.0-py3.8.egg\telegramer\__init__.py", line 53, in load_libs
    egg = pkg_resources.require("Telegramer")[0]
  File "pkg_resources\__init__.py", line 886, in require
  File "pkg_resources\__init__.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'Telegramer' distribution was not found and is required by the application

```

Here's my about page^
![deluge about](https://user-images.githubusercontent.com/36101416/187488031-a6a9f7b8-26c5-404c-acbe-5a7f74a55269.png)

**Comment by noam09** [comment]
@dkgitdev thank you for the report and the contribution! Sorry for the huge delay, real life stuff gets in the way.
I am looking into how I can better manage (automate) these dependencies, which is why I still haven't merged your changes. Greatly appreciated!

**Comment by dkgitdev** [comment]
Thanks for the heads up

**Comment by noam09** [comment]
Also forgot to ask, which Python version do you have installed?

**Comment by dkgitdev** [comment]
I suppose it was 3.8, although it was a long time ago and I'm not sure now :)

I've wiped my OS since then
