### ISSUE TITLE
[BUG] Telegramer does not start after updating deluge

### ISSUE THREAD

**Issue by Lukki4** [noam09/deluge-telegramer#39]
**Describe the bug**
  File "/usr/lib/python3.11/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
The python version has changed.

**To Reproduce**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/112572763/209398757-73bd5a65-adbd-4705-90ba-80fffd66665e.png)

**Logs**
[custom-init] No custom files found, skipping...
22:16:57 [ERROR   ][deluge.pluginmanagerbase      :1622] Unable to instantiate plugin 'Telegramer' from '/config/plugins/Telegramer-2.0.5.0-py3.10.egg'!
22:16:57 [ERROR   ][deluge.pluginmanagerbase      :1622] The 'Telegramer' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plugins/Telegramer-2.0.5.0-py3.10.egg/telegramer/__init__.py", line 64, in __init__
    load_libs()
  File "/config/plugins/Telegramer-2.0.5.0-py3.10.egg/telegramer/__init__.py", line 53, in load_libs
    egg = pkg_resources.require("Telegramer")[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Telegramer' distribution was not found and is required by the application

**OS and Version:**
 - OS: Linux
 - Deluge version: [e.g. `2.1.1`]
`deluge --version` or `deluged --version`

**Comment by noam09** [comment]
Hey @Lukki4 , thanks for reporting this. 
What version of Deluge do you have installed? And which version of the plugin are you trying to enable?

**Comment by Lukki4** [comment]
> Hey @Lukki4 , thanks for reporting this. What version of Deluge do you have installed? And which version of the plugin are you trying to enable?
![image](https://user-images.githubusercontent.com/112572763/209498105-a994fdb2-39d8-4d7e-95e5-97ee7440dd88.png)

plugin: Telegramer-2.0.5.0-py3.10.egg

**Comment by noam09** [comment]
Can you please try using this .egg instead (based on Python 11)?
https://github.com/noam09/deluge-telegramer/releases/download/v2.0.5.0/Telegramer-2.0.5.0-py3.11.egg

**Comment by Lukki4** [comment]
> Can you please try using this .egg instead (based on Python 11)? https://github.com/noam09/deluge-telegramer/releases/download/v2.0.5.0/Telegramer-2.0.5.0-py3.11.egg

Great! This version works. Thanks!
