### ISSUE TITLE
Not working in Windows 10/Web-Ui

### ISSUE THREAD

**Issue by vakulenchuk** [noam09/deluge-telegramer#5]
Installed the plugin, created the bot, configured proper ids and /started the bot. Not receiving any notifications here, test also seems to fail. Let me know if you need more info.

**Comment by noam09** [comment]
Hi @vakulenchuk, have you tried restarting Deluge after installing the plugin?

Also, can you please save a debug log in order to reveal more information on what is causing it to fail? 

http://dev.deluge-torrent.org/wiki/Troubleshooting#WindowsSpecificLogging

**Comment by vakulenchuk** [comment]
Yes, I have tried a restart.

Here is a debug log from deluged-debug.exe
[deluge.txt](https://github.com/noam09/deluge-telegramer/files/1057328/deluge.txt)

**Comment by noam09** [comment]
Perfect, thank you. I will make a few changes and create a new .egg for you to test. Would you mind emailing me so I can send you the attachment directly? My email is on my profile.
