### ISSUE TITLE
Win 7 x64 Py 2.7 /add crash

### ISSUE THREAD

**Issue by BlackLynxBY** [noam09/deluge-telegramer#6]
Deluge crash if plugin "label" are disabled.
At Telegram we are see dialog:
/add
Select Directory
"ISO"
_At this point, the application crash. if the plugin 'label' disabled_
Select Label
"No Label"
...

**Comment by noam09** [comment]
Hey @BlackLynxBY, can you please post a debug log of the error? The plugin's debug logs start with "Telegramer", make sure to remove any information which may be sensitive. 
Thank you!

**Comment by BlackLynxBY** [comment]
[DEBUG   ] 20:35:18 gtkui:74 Telegramer: applying prefs for Telegramer
[DEBUG   ] 20:35:18 core:625 2017-06-19 20:35:18 # Telegramer: Set config
[DEBUG   ] 20:35:18 config:218 Setting 'listen_ports' to [6881, 6891] of <type 'list'>
[DEBUG   ] 20:35:18 config:218 Setting 'outgoing_ports' to [0, 0] of <type 'list'>
[DEBUG   ] 20:35:18 pluginmanager:104 run_on_show_prefs
[DEBUG   ] 20:35:18 core:110 Handled Notification Events: [('GtkUILogMessageEvent', 'Emitted when a message has been written to the log.'), ('TorrentFinishedEvent', 'Emitted when a torrent finishes downloading.'), ('YARSSConfigChangedEvent', 'Emitted when the config has been changed.')]
[DEBUG   ] 20:35:18 core:650 2017-06-19 20:35:18 # Telegramer: Get config
[DEBUG   ] 20:35:18 preferences:919 on_plugin_selection_changed
[INFO    ] 20:35:18 server:666 Starting server in PID 1180.
[INFO    ] 20:35:18 server:679 Serving on 0.0.0.0:8112 view at http://0.0.0.0:8112
[DEBUG   ] 20:35:18 json_api:330 Registering method: webapi.add_torrent
[DEBUG   ] 20:35:18 json_api:330 Registering method: webapi.get_api_version
[DEBUG   ] 20:35:18 json_api:330 Registering method: webapi.get_torrents
[DEBUG   ] 20:35:18 json_api:330 Registering method: webapi.remove_torrent
[DEBUG   ] 20:35:18 component:256 Deregistering Component: WebPlugin.webapi
[DEBUG   ] 20:35:18 pluginbase:77 WebPlugin initialized..
[INFO    ] 20:35:18 webui:18 Enabling WebAPI plugin WEB ...
[DEBUG   ] 20:35:18 pluginmanagerbase:156 Adding webapi to enabled_plugins list in config
[INFO    ] 20:35:18 pluginmanagerbase:158 Plugin webapi enabled..
[INFO    ] 20:35:18 pluginmanager:108 'webapi' plugin contains no WebUI code, ignoring WebUI enable call.
[ERROR   ] 20:35:18 __init__:56 Appending to sys.path: 'c:\users\black lynx\appdata\roaming\deluge\plugins\telegramer-1.1.1-py2.7.egg/telegramer/include'
[DEBUG   ] 20:35:18 pluginbase:77 WebPlugin initialized..
[DEBUG   ] 20:35:18 pluginmanagerbase:156 Adding Telegramer to enabled_plugins list in config
[INFO    ] 20:35:18 pluginmanagerbase:158 Plugin Telegramer enabled..
[DEBUG   ] 20:35:18 pluginmanager:115 adding script Telegramer for telegramer.js
[DEBUG   ] 20:35:18 pluginmanager:119 adding debug script Telegramer for telegramer.js
[DEBUG   ] 20:35:18 pluginbase:77 WebPlugin initialized..
[DEBUG   ] 20:35:18 webui:52 Enabling Web UI notifications
[DEBUG   ] 20:35:18 pluginmanagerbase:156 Adding Notifications to enabled_plugins list in config
[INFO    ] 20:35:18 pluginmanagerbase:158 Plugin Notifications enabled..
[DEBUG   ] 20:35:18 pluginmanager:115 adding script Notifications for notifications.js
[DEBUG   ] 20:35:18 pluginmanager:119 adding debug script Notifications for notifications.js
[INFO    ] 20:35:18 pluginmanager:108 'WebUi' plugin contains no WebUI code, ignoring WebUI enable call.
[INFO    ] 20:35:18 pluginmanager:108 'YaRSS2' plugin contains no WebUI code, ignoring WebUI enable call.
[DEBUG   ] 20:35:18 rpcserver:469 intevents: {}
[DEBUG   ] 20:35:18 rpcserver:469 intevents: {}
[DEBUG   ] 20:35:18 preferences:869 on_button_ok_clicked
[WARNING ] 20:35:18 common:577 ipv6 check unavailable on windows
[DEBUG   ] 20:35:18 pluginmanager:112 run_on_apply_prefs
[DEBUG   ] 20:35:18 gtkui:471 applying prefs for Notifications
[DEBUG   ] 20:35:18 gtkui:490 Old Default sound file: C:\Users\Black Lynx\Downloads New one: C:\Users\Black Lynx\Downloads
[DEBUG   ] 20:35:18 gtkui:493 Custom sound for event "GtkUILogMessageEvent": Downloads
[DEBUG   ] 20:35:18 gtkui:493 Custom sound for event "TorrentFinishedEvent": Downloads
[DEBUG   ] 20:35:18 gtkui:493 Custom sound for event "YARSSConfigChangedEvent": Downloads
[DEBUG   ] 20:35:18 core:110 Handled Notification Events: [('GtkUILogMessageEvent', 'Emitted when a message has been written to the log.'), ('TorrentFinishedEvent', 'Emitted when a torrent finishes downloading.'), ('YARSSConfigChangedEvent', 'Emitted when the config has been changed.')]
[DEBUG   ] 20:35:18 gtkui:67 applying prefs for WebUi
[INFO    ] 20:35:18 server:696 Shutting down webserver
[DEBUG   ] 20:35:18 pluginmanager:86 'webapi' plugin contains no WebUI code, ignoring WebUI disable call.
[DEBUG   ] 20:35:18 webui:55 Disabling Web UI notifications
[DEBUG   ] 20:35:18 component:256 Deregistering Component: WebPlugin.Notifications
[INFO    ] 20:35:18 pluginmanagerbase:170 Plugin Notifications disabled..
[DEBUG   ] 20:35:18 component:256 Deregistering Component: WebPlugin.Telegramer
[INFO    ] 20:35:18 pluginmanagerbase:170 Plugin Telegramer disabled..
[DEBUG   ] 20:35:18 pluginmanager:86 'webapi' plugin contains no WebUI code, ignoring WebUI disable call.
[DEBUG   ] 20:35:18 server:700 Saving configuration file
[DEBUG   ] 20:35:18 config:427 Saving new config file C:\Users\Black Lynx\AppData\Roaming\deluge\web.conf.new
[DEBUG   ] 20:35:18 config:440 Backing up old config file to C:\Users\Black Lynx\AppData\Roaming\deluge\web.conf~
[DEBUG   ] 20:35:18 config:448 Moving new config file C:\Users\Black Lynx\AppData\Roaming\deluge\web.conf.new to C:\Users\Black Lynx\AppData\Roaming\deluge\web.conf..
[DEBUG   ] 20:35:18 gtkui:74 Telegramer: applying prefs for Telegramer
[DEBUG   ] 20:35:18 core:625 2017-06-19 20:35:18 # Telegramer: Set config
[INFO    ] 20:35:18 server:666 Starting server in PID 1180.
[INFO    ] 20:35:18 server:679 Serving on 0.0.0.0:8112 view at http://0.0.0.0:8112
[WARNING ] 20:35:18 pluginmanagerbase:134 Cannot enable already enabled plugin webapi
[INFO    ] 20:35:18 pluginmanager:108 'webapi' plugin contains no WebUI code, ignoring WebUI enable call.
[ERROR   ] 20:35:18 __init__:56 Appending to sys.path: 'c:\users\black lynx\appdata\roaming\deluge\plugins\telegramer-1.1.1-py2.7.egg/telegramer/include'
[DEBUG   ] 20:35:18 pluginbase:77 WebPlugin initialized..
[DEBUG   ] 20:35:18 pluginmanagerbase:156 Adding Telegramer to enabled_plugins list in config
[INFO    ] 20:35:18 pluginmanagerbase:158 Plugin Telegramer enabled..
[DEBUG   ] 20:35:18 pluginmanager:115 adding script Telegramer for telegramer.js
[DEBUG   ] 20:35:18 pluginmanager:119 adding debug script Telegramer for telegramer.js
[DEBUG   ] 20:35:18 pluginbase:77 WebPlugin initialized..
[DEBUG   ] 20:35:18 webui:52 Enabling Web UI notifications
[DEBUG   ] 20:35:18 pluginmanagerbase:156 Adding Notifications to enabled_plugins list in config
[INFO    ] 20:35:18 pluginmanagerbase:158 Plugin Notifications enabled..
[DEBUG   ] 20:35:18 pluginmanager:115 adding script Notifications for notifications.js
[DEBUG   ] 20:35:18 pluginmanager:119 adding debug script Notifications for notifications.js
[INFO    ] 20:35:18 pluginmanager:108 'WebUi' plugin contains no WebUI code, ignoring WebUI enable call.
[INFO    ] 20:35:18 pluginmanager:108 'YaRSS2' plugin contains no WebUI code, ignoring WebUI enable call.
[DEBUG   ] 20:35:18 bot:1246 No new updates found.
[DEBUG   ] 20:35:18 bot:126 []
[DEBUG   ] 20:35:18 bot:127 Exiting: getUpdates
[DEBUG   ] 20:35:18 bot:124 Entering: getUpdates
[DEBUG   ] 20:35:19 alertmanager:124 udp_error_alert: UDP error: РЈРґР°Р»РµРЅРЅС‹Р№ С…РѕСЃС‚ РїСЂРёРЅСѓРґРёС‚РµР»СЊРЅРѕ СЂР°Р·РѕСЂРІР°Р» СЃСѓС‰РµСЃС‚РІСѓСЋС‰РµРµ РїРѕРґРєР»СЋС‡РµРЅРёРµ from: 82.209.216.189
[DEBUG   ] 20:35:23 config:427 Saving new config file C:\Users\Black Lynx\AppData\Roaming\deluge\core.conf.new
[DEBUG   ] 20:35:23 config:440 Backing up old config file to C:\Users\Black Lynx\AppData\Roaming\deluge\core.conf~
[DEBUG   ] 20:35:23 config:448 Moving new config file C:\Users\Black Lynx\AppData\Roaming\deluge\core.conf.new to C:\Users\Black Lynx\AppData\Roaming\deluge\core.conf..
[DEBUG   ] 20:35:23 alertmanager:124 udp_error_alert: UDP error: РЈРґР°Р»РµРЅРЅС‹Р№ С…РѕСЃС‚ РїСЂРёРЅСѓРґРёС‚РµР»СЊРЅРѕ СЂР°Р·РѕСЂРІР°Р» СЃСѓС‰РµСЃС‚РІСѓСЋС‰РµРµ РїРѕРґРєР»СЋС‡РµРЅРёРµ from: 62.165.218.91
[DEBUG   ] 20:35:26 bot:1244 Getting updates: [637298814]
[DEBUG   ] 20:35:26 bot:126 [<telegram.update.Update object at 0x046EF850>]
[DEBUG   ] 20:35:26 bot:127 Exiting: getUpdates
[DEBUG   ] 20:35:26 dispatcher:224 Processing Update: {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [{'length': 4, 'type': u'bot_command', 'offset': 0}], 'text': u'/add', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'BlackLynx', 'first_name': u'Alexey', 'last_name': u'Volkov', 'type': '', 'id': 103023993}, 'supergroup_chat_created': False, 'chat': {'username': u'BlackLynx', 'first_name': u'Alexey', 'all_members_are_admins': False, 'title': '', 'last_name': u'Volkov', 'type': u'private', 'id': 103023993}, 'photo': [], 'date': 1497893742, 'group_chat_created': False, 'caption': '', 'message_id': 109, 'new_chat_title': ''}, 'update_id': 637298814}
[DEBUG   ] 20:35:26 conversationhandler:147 selecting conversation (103023993, 103023993) with state None
[DEBUG   ] 20:35:26 core:335 2017-06-19 20:35:26 # Telegramer: VIDEO E:\VIDEO\
[DEBUG   ] 20:35:26 core:335 2017-06-19 20:35:26 # Telegramer: ISO E:\ISO\
[DEBUG   ] 20:35:26 core:335 2017-06-19 20:35:26 # Telegramer: ALL D:\torrents\
[DEBUG   ] 20:35:26 core:340 2017-06-19 20:35:26 # Telegramer: ISO
[DEBUG   ] 20:35:26 core:340 2017-06-19 20:35:26 # Telegramer: ALL
[DEBUG   ] 20:35:26 core:340 2017-06-19 20:35:26 # Telegramer: VIDEO
[DEBUG   ] 20:35:26 bot:124 Entering: sendMessage
[DEBUG   ] 20:35:26 bot:124 Entering: getUpdates
[DEBUG   ] 20:35:26 bot:126 {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [{'length': 7, 'type': u'bot_command', 'offset': 82}], 'text': u'Which category/directory?\nRemember to quote directory paths ("/path/to/dir")\nSend /cancel at any time to abort', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'DelugerBot', 'first_name': u'Deluger', 'last_name': '', 'type': '', 'id': 429984094}, 'supergroup_chat_created': False, 'chat': {'username': u'BlackLynx', 'first_name': u'Alexey', 'all_members_are_admins': False, 'title': '', 'last_name': u'Volkov', 'type': u'private', 'id': 103023993}, 'photo': [], 'date': 1497893742, 'group_chat_created': False, 'caption': '', 'message_id': 110, 'new_chat_title': ''}
[DEBUG   ] 20:35:26 bot:127 Exiting: sendMessage
[DEBUG   ] 20:35:27 alertmanager:124 udp_error_alert: UDP error: РЈРґР°Р»РµРЅРЅС‹Р№ С…РѕСЃС‚ РїСЂРёРЅСѓРґРёС‚РµР»СЊРЅРѕ СЂР°Р·РѕСЂРІР°Р» СЃСѓС‰РµСЃС‚РІСѓСЋС‰РµРµ РїРѕРґРєР»СЋС‡РµРЅРёРµ from: 31.180.81.6
[DEBUG   ] 20:35:28 alertmanager:124 udp_error_alert: UDP error: РЈРґР°Р»РµРЅРЅС‹Р№ С…РѕСЃС‚ РїСЂРёРЅСѓРґРёС‚РµР»СЊРЅРѕ СЂР°Р·РѕСЂРІР°Р» СЃСѓС‰РµСЃС‚РІСѓСЋС‰РµРµ РїРѕРґРєР»СЋС‡РµРЅРёРµ from: 82.209.216.189
[DEBUG   ] 20:35:28 bot:1244 Getting updates: [637298815]
[DEBUG   ] 20:35:28 bot:126 [<telegram.update.Update object at 0x049FEAB0>]
[DEBUG   ] 20:35:28 bot:127 Exiting: getUpdates
[DEBUG   ] 20:35:28 dispatcher:224 Processing Update: {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [], 'text': u'Use Default Settings', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'BlackLynx', 'first_name': u'Alexey', 'last_name': u'Volkov', 'type': '', 'id': 103023993}, 'supergroup_chat_created': False, 'chat': {'username': u'BlackLynx', 'first_name': u'Alexey', 'all_members_are_admins': False, 'title': '', 'last_name': u'Volkov', 'type': u'private', 'id': 103023993}, 'photo': [], 'date': 1497893744, 'group_chat_created': False, 'caption': '', 'message_id': 111, 'new_chat_title': ''}, 'update_id': 637298815}
[DEBUG   ] 20:35:28 conversationhandler:147 selecting conversation (103023993, 103023993) with state 0
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.add
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.get_config
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.get_labels
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.get_options
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.remove
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.set_config
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.set_options
[DEBUG   ] 20:35:28 rpcserver:398 Registering method: label.set_torrent
[DEBUG   ] 20:35:28 pluginbase:57 CorePlugin initialized..
[INFO    ] 20:35:28 core:97 *** Start Label plugin ***
[DEBUG   ] 20:35:28 pluginmanager:107 Registering status field label with PluginManager
[DEBUG   ] 20:35:28 configmanager:111 Getting config 'label.conf'
[DEBUG   ] 20:35:28 configmanager:111 Getting config 'core.conf'
[DEBUG   ] 20:35:28 core:165 [u'grimm']
[DEBUG   ] 20:35:28 core:120 Label plugin enabled..
[DEBUG   ] 20:35:28 pluginmanagerbase:156 Adding Label to enabled_plugins list in config
[INFO    ] 20:35:28 pluginmanagerbase:158 Plugin Label enabled..
[DEBUG   ] 20:35:28 rpcserver:469 intevents: {}
[DEBUG   ] 20:35:28 pluginbase:62 GtkPlugin initialized..
[DEBUG   ] 20:35:28 __init__:92 add items to torrentview-popup menu.
[DEBUG   ] 20:35:28 __init__:109 add columns
[DEBUG   ] 20:35:28 torrentview:627 on_selection_changed

**Comment by noam09** [comment]
I can't seem to find a crash in the log you posted... Do you mind posting another one when the crash happens? Does Deluge crash or just the plugin?
Also, do you have the Label plugin installed? Is it disabled?

**Comment by BlackLynxBY** [comment]
Plugin installed and disabled.
https://drive.google.com/drive/folders/0By3cBieDM_-adW1BMVVhTFZNVE0?usp=sharing

**Comment by BlackLynxBY** [comment]
https://drive.google.com/drive/folders/0By3cBieDM_-adW1BMVVhTFZNVE0?usp=sharing

**Comment by noam09** [comment]
Please try the latest version and post back with results/debug log: 
https://github.com/noam09/deluge-telegramer/releases/download/v1.1.2/Telegramer-1.1.2-py2.7.egg

**Comment by BlackLynxBY** [comment]
Deluge launched, plugin "Label" disabled.
Starting bot.
/ADD
Deluge enable and start plugin "Label".
But in next time, Deluge crash again. Photo and log in folder on GD.
I test it once more - no errors... I make next test in evening.

**Comment by BlackLynxBY** [comment]
evening test
Logs and video uploaded to GD
Test 1 - fail
Test 2 - OK
Test 3 - OK
Before and after every test plugin disabled, deluge reloaded.
