### ISSUE TITLE
Bot working but not replying

### ISSUE THREAD

**Issue by pifiuk** [noam09/deluge-telegramer#8]
Hello, 

After running for a little while, the bot still works sending me notifications of torrents added, downloaded etc but I can no longer interact adding or listing torrents. 

I have tried reloading.

**Comment by noam09** [comment]
Hi @pifiuk, thanks for posting the issue. 
Does this happen after a set amount of time while the host is running, and if so, how long before it stops receiving commands? 
Does it only occur following sleep/suspend/hibernation?

**Comment by pifiuk** [comment]
I can't be sure, i'm running it on a server at home that runs 24/7 so there is no sleep/suspend or hibernation. Since I can't get it working again I don't know how to 'time' it.

**Comment by noam09** [comment]
If it runs 24/7 then it's unrelated to the suspend/hibernate "known issue". I will hopefully have time to look into it this week.
Are you running the latest commit or the last .egg from Releases?

**Comment by pifiuk** [comment]
I'm running Deluge 1.3.14 (the latest .egg crashed Deluge 1.3.15) and yes i'm using the last .egg.

**Comment by noam09** [comment]
Can you try running the latest code? Building an .egg from source is rather straightforward, I mentioned it in the README.

**Comment by akaishauri** [comment]
Hello,
Can confirm this issue in the latest code. Bot stops responding after 2 or 3 days. Not using sleep/suspend either.

**Comment by noam09** [comment]
Thanks for confirming, @akaishauri. 
I haven't forgotten about this, I hope to find the time to fix it soon. It's likely something to do with tge way threads are handled. I probably need to borrow some of the code from the old version (which used a different Telegram API wrapper) where I had the bot running full-time, even with sleep/suspend.

**Comment by noam09** [comment]
@akaishauri and @pifiuk, please try out the latest commit and see if it has any affect on the issue. 
I will upload a new .egg to the releases page ASAP, but you can also build the .egg from source. :) 
**EDIT:** https://github.com/noam09/deluge-telegramer/releases/tag/v1.1.4

**Comment by akaishauri** [comment]
@noam09 , I have installed v1.1.4, let's see what happens after a few days.

**Comment by BlackLynxBY** [comment]
Win 7 x64, Deluge 1.3.15, Telegramer 1.1.4.
After updating from 1.1.2, the plugin is not activated.
Debug-log:
[DEBUG   ] 21:25:54 preferences:907 on_plugin_toggled
[ERROR   ] 21:25:54 __init__:56 Appending to sys.path: 'c:\users\black lynx\appdata\roaming\deluge\plugins\telegramer-1.1.4-py2.7.egg/telegramer/include'
[ERROR   ] 21:25:54 core:79 2017-09-16 21:25:54 # Telegramer: Import error - No module named certifi
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/telegramer/core.py", line 61, in <module>
    from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, Bot)
  File "build/bdist.linux-x86_64/egg/telegramer/include/telegram/__init__.py", line 94, in <module>
  File "build/bdist.linux-x86_64/egg/telegramer/include/telegram/bot.py", line 34, in <module>
  File "build/bdist.linux-x86_64/egg/telegramer/include/telegram/utils/request.py", line 31, in <module>
ImportError: No module named certifi

[ERROR   ] 21:25:54 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 21:25:54 pluginmanagerbase:147 name 'CorePluginBase' is not defined
Traceback (most recent call last):
  File "deluge\pluginmanagerbase.py", line 144, in enable_plugin
  File "build/bdist.linux-x86_64/egg/telegramer/__init__.py", line 61, in __init__
    from core import Core as _plugin_cls
  File "build/bdist.linux-x86_64/egg/telegramer/core.py", line 150, in <module>
    class Core(CorePluginBase):
NameError: name 'CorePluginBase' is not defined
[DEBUG   ] 21:25:54 preferences:919 on_plugin_selection_changed

**Comment by noam09** [comment]
@BlackLynxBY please try v1.1.5
https://github.com/noam09/deluge-telegramer/releases/tag/v1.1.5

**Comment by BlackLynxBY** [comment]
[DEBUG   ] 22:03:35 preferences:907 on_plugin_toggled
[ERROR   ] 22:03:35 __init__:56 Appending to sys.path: 'c:\users\black lynx\appdata\roaming\deluge\plugins\telegramer-1.1.5-py2.7.egg/telegramer/include'
[ERROR   ] 22:03:35 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 22:03:35 pluginmanagerbase:147 name 'log' is not defined
Traceback (most recent call last):
  File "deluge\pluginmanagerbase.py", line 144, in enable_plugin
  File "build/bdist.linux-x86_64/egg/telegramer/__init__.py", line 61, in __init__
    from core import Core as _plugin_cls
  File "build/bdist.linux-x86_64/egg/telegramer/core.py", line 61, in <module>
  File "build/bdist.linux-x86_64/egg/telegramer/include/telegram/__init__.py", line 94, in <module>
  File "build/bdist.linux-x86_64/egg/telegramer/include/telegram/bot.py", line 34, in <module>
  File "build/bdist.linux-x86_64/egg/telegramer/include/telegram/utils/request.py", line 34, in <module>
NameError: name 'log' is not defined
[DEBUG   ] 22:03:35 preferences:919 on_plugin_selection_changed

**Comment by noam09** [comment]
Sorry about that @BlackLynxBY - please try:
https://github.com/noam09/deluge-telegramer/releases/tag/v1.1.6
I hope this one solves it...

**Comment by BlackLynxBY** [comment]
Thanks 1.1.6, works!
Do not worry about us. You are the only one who writes for Windows users.
Thank you!

**Comment by noam09** [comment]
@akaishauri - how is it holding up so far?

**Comment by akaishauri** [comment]
Looks like 1.1.6 still has this issue.

**Comment by noam09** [comment]
That's a shame... Can you tell if it stops only after several days of running, or even after a few hours? Can you try running Deluge in debugging mode so that maybe the logs point to the issue?

Edit: @pifiuk, are you seeing a change with the latest .egg?

**Comment by noam09** [comment]
Please reopen if issues persist. :)
