### ISSUE TITLE
Can't connect to Daemon after adding new torrent

### ISSUE THREAD

**Issue by wolverinevn** [noam09/deluge-telegramer#9]
After adding a new torrent (magnet) via Telegramer, deluge-web can't connect to Daemon anymore. Connection manager showing Offline Daemon, can not start, connection lost. Torrents are still downloading, /list command worked.
System: Pi 3 running newest Jessie, Deluged ver 1.3.13, max connection: 200.

**Comment by noam09** [comment]
Hi @wolverinevn, sorry to hear Telegramer might be causing issues. When you say deluge-web can't connect, do you mean you can't connect via browser (WebUI)? Or the daemon itself fails to connect? When deluge-web fails to connect, does adding torrents via Telegramer still work? 

Are there any debug logs you can provide to help better understand the issue? deluged logs, deluge-web logs?

**Comment by noam09** [comment]
Please reopen if issues persist. :)
